GET /kaimemo HTTP/1.1 
Host: localhost:3000
content-type: application/json 

{ 
  "name": "Hello,NotionAPI!",
  "tag": "食費"
}

POST /kaimemo HTTP/1.1 
Host: localhost:3000
content-type: application/json 

{ 
  "name": "Hello,deploy rendor api!",
  "tag": "食費"
}

DELETE /kaimemo/189c9692-0f0c-818b-a91a-defc35c6505d HTTP/1.1 
Host: localhost:3000
content-type: application/json 

{ 
  "data": "Hello, World!"
}


# localテスト用

POST /openai/analyze/2/receipt/result HTTP/1.1 
Host: localhost:3000
content-type: application/json 

{ 
  "total": 100,
  "categoryID": 3,
  "s3FilePath": "4e4cbd8d-f39f-4eb9-8ba0-7de6b98317bb-2-3-20250605233119.jpg",
  "items": [
    {
      "name": "test",
      "price": 100  
    }
  ]
}
